Output theme.gif

Set Width 800
Set Height 740
Set Padding 80

Hide
Type "go build -o theme ."
Enter
Ctrl+L
Sleep 500ms
Type "clear && ./theme" Enter
Show

Sleep 2s

Enter

Screenshot default-theme.png

Tab 4
Down 1
Enter

Screenshot dracula-theme.png

Tab 4
Down 2
Enter

Screenshot basesixteen-theme.png

Tab 4
Down 3
Enter

Screenshot charm-theme.png

Tab 4
Down 4
Enter

Screenshot catppuccin-theme.png

Sleep 1s

Hide
Type "rm theme"
Enter
