Output text.gif

Set Width 1000
Set Padding 40
Set Height 450
Set FontSize 28

Hide
  Type "go build ." Enter
  Ctrl+L
  Type "./text" Enter
  Sleep 500ms
Show

Sleep 1s
Type "Once upon a time, in the heart of a lush, enchanted forest, there existed a peculiar village named Charm Dale. This village was unlike any other; its cobblestone streets were lined with houses crafted from the timber of ancient, towering trees that sparkled under the sunlight."
Sleep 4s

Hide
Type "rm text" Enter
