Output taco.gif

Set Height 600
Set Width 1200

Hide
Type "go build -o taco ." Enter
Ctrl+L
Show

Type "./taco"
Sleep 500ms
Enter

Sleep 1s
Type "n"
Sleep 1s
Down
Sleep 500ms Enter
Sleep 1s
Up
Sleep 500ms Enter
Sleep 1s
Down@500ms 2
Sleep 500ms Enter
Sleep 1s
Down@500ms 3
Space
Sleep 500ms Enter
Sleep 500ms Enter

Sleep 1s

Type "Glen"
Sleep 500ms Enter

Sleep 1s
Type "Extra spicy please!"
Sleep 500ms Tab

Sleep 1s
Left
Sleep 1s Enter

Sleep 5s

Hide
Type "rm taco" Enter
Sleep 1s
Show
