Output sec-input.gif

Set Height 600
Set Width 1000

Hide
	Type "go build -o accessible ." Enter
	Type "clear && ./accessible" Enter
	Sleep 1s
Show

Type "Jeremy"
Sleep 1s
Enter

Type "password"
Sleep 1.5s
Enter

Sleep 3s

Type "1"
Sleep 1.5s
Enter

Type "3"
Sleep 1.5s
Enter

Type "2"
Sleep 1.5s
Enter

Type "0"
Sleep 1.5s
Enter

Type "1"
Sleep 1.5s
Enter

Type "main.go"
Sleep 1.5s
Enter

Type "n"
Sleep 1.5s
Enter

Sleep 3s

Hide
Type "rm accessible" Enter
Sleep 1s
	
