name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22, stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v -race ./...
  spinner:
    strategy:
      matrix:
        go-version: [1.22, stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          working-directory: ./spinner
      - run: go mod download
        working-directory: ./spinner
      - run: go build -v ./...
        working-directory: ./spinner
      - run: go test -v -race ./...
        working-directory: ./spinner
  examples:
    strategy:
      matrix:
        go-version: [1.22, stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          working-directory: ./examples
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go mod download
        working-directory: ./examples
      - run: go build -v ./...
        working-directory: ./examples
      - run: go test -v -race ./...
        working-directory: ./examples
